package Nimbus_Rating_DB;
// Generated 07-Oct-2011 14:20:14 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * RejectedCdr generated by hbm2java
 */
public class RejectedCdr  implements java.io.Serializable {


     private int id;
     private String originalData;
     private String rejectionReason;
     private int rejectionTimestamp;
     private int state;
     private String suspenseCategory;
     private String diagnosticInfo;
     private Date entryDate;
     private String callReference;
     private Integer network;
     private String callType;
     private String remoteNetwork;
     private String supplierSwitch;
     private String direction;
     private String portingPrefix;
     private String cli;
     private String destination;
     private String usageType;
     private String numberType;
     private Date dateTime;
     private Integer duration;
     private String billingEntity;
     private String displayNumber;
     private String platform;
     private String machine;
     private String linkNumber;
     private String cdrGuid;
     private String callIdentifier;

    public RejectedCdr() {
    }

	
    public RejectedCdr(int id, String originalData, String rejectionReason, int rejectionTimestamp, int state, String suspenseCategory) {
        this.id = id;
        this.originalData = originalData;
        this.rejectionReason = rejectionReason;
        this.rejectionTimestamp = rejectionTimestamp;
        this.state = state;
        this.suspenseCategory = suspenseCategory;
    }
    public RejectedCdr(int id, String originalData, String rejectionReason, int rejectionTimestamp, int state, String suspenseCategory, String diagnosticInfo, Date entryDate, String callReference, Integer network, String callType, String remoteNetwork, String supplierSwitch, String direction, String portingPrefix, String cli, String destination, String usageType, String numberType, Date dateTime, Integer duration, String billingEntity, String displayNumber, String platform, String machine, String linkNumber, String cdrGuid, String callIdentifier) {
       this.id = id;
       this.originalData = originalData;
       this.rejectionReason = rejectionReason;
       this.rejectionTimestamp = rejectionTimestamp;
       this.state = state;
       this.suspenseCategory = suspenseCategory;
       this.diagnosticInfo = diagnosticInfo;
       this.entryDate = entryDate;
       this.callReference = callReference;
       this.network = network;
       this.callType = callType;
       this.remoteNetwork = remoteNetwork;
       this.supplierSwitch = supplierSwitch;
       this.direction = direction;
       this.portingPrefix = portingPrefix;
       this.cli = cli;
       this.destination = destination;
       this.usageType = usageType;
       this.numberType = numberType;
       this.dateTime = dateTime;
       this.duration = duration;
       this.billingEntity = billingEntity;
       this.displayNumber = displayNumber;
       this.platform = platform;
       this.machine = machine;
       this.linkNumber = linkNumber;
       this.cdrGuid = cdrGuid;
       this.callIdentifier = callIdentifier;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getOriginalData() {
        return this.originalData;
    }
    
    public void setOriginalData(String originalData) {
        this.originalData = originalData;
    }
    public String getRejectionReason() {
        return this.rejectionReason;
    }
    
    public void setRejectionReason(String rejectionReason) {
        this.rejectionReason = rejectionReason;
    }
    public int getRejectionTimestamp() {
        return this.rejectionTimestamp;
    }
    
    public void setRejectionTimestamp(int rejectionTimestamp) {
        this.rejectionTimestamp = rejectionTimestamp;
    }
    public int getState() {
        return this.state;
    }
    
    public void setState(int state) {
        this.state = state;
    }
    public String getSuspenseCategory() {
        return this.suspenseCategory;
    }
    
    public void setSuspenseCategory(String suspenseCategory) {
        this.suspenseCategory = suspenseCategory;
    }
    public String getDiagnosticInfo() {
        return this.diagnosticInfo;
    }
    
    public void setDiagnosticInfo(String diagnosticInfo) {
        this.diagnosticInfo = diagnosticInfo;
    }
    public Date getEntryDate() {
        return this.entryDate;
    }
    
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }
    public String getCallReference() {
        return this.callReference;
    }
    
    public void setCallReference(String callReference) {
        this.callReference = callReference;
    }
    public Integer getNetwork() {
        return this.network;
    }
    
    public void setNetwork(Integer network) {
        this.network = network;
    }
    public String getCallType() {
        return this.callType;
    }
    
    public void setCallType(String callType) {
        this.callType = callType;
    }
    public String getRemoteNetwork() {
        return this.remoteNetwork;
    }
    
    public void setRemoteNetwork(String remoteNetwork) {
        this.remoteNetwork = remoteNetwork;
    }
    public String getSupplierSwitch() {
        return this.supplierSwitch;
    }
    
    public void setSupplierSwitch(String supplierSwitch) {
        this.supplierSwitch = supplierSwitch;
    }
    public String getDirection() {
        return this.direction;
    }
    
    public void setDirection(String direction) {
        this.direction = direction;
    }
    public String getPortingPrefix() {
        return this.portingPrefix;
    }
    
    public void setPortingPrefix(String portingPrefix) {
        this.portingPrefix = portingPrefix;
    }
    public String getCli() {
        return this.cli;
    }
    
    public void setCli(String cli) {
        this.cli = cli;
    }
    public String getDestination() {
        return this.destination;
    }
    
    public void setDestination(String destination) {
        this.destination = destination;
    }
    public String getUsageType() {
        return this.usageType;
    }
    
    public void setUsageType(String usageType) {
        this.usageType = usageType;
    }
    public String getNumberType() {
        return this.numberType;
    }
    
    public void setNumberType(String numberType) {
        this.numberType = numberType;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }
    public Integer getDuration() {
        return this.duration;
    }
    
    public void setDuration(Integer duration) {
        this.duration = duration;
    }
    public String getBillingEntity() {
        return this.billingEntity;
    }
    
    public void setBillingEntity(String billingEntity) {
        this.billingEntity = billingEntity;
    }
    public String getDisplayNumber() {
        return this.displayNumber;
    }
    
    public void setDisplayNumber(String displayNumber) {
        this.displayNumber = displayNumber;
    }
    public String getPlatform() {
        return this.platform;
    }
    
    public void setPlatform(String platform) {
        this.platform = platform;
    }
    public String getMachine() {
        return this.machine;
    }
    
    public void setMachine(String machine) {
        this.machine = machine;
    }
    public String getLinkNumber() {
        return this.linkNumber;
    }
    
    public void setLinkNumber(String linkNumber) {
        this.linkNumber = linkNumber;
    }
    public String getCdrGuid() {
        return this.cdrGuid;
    }
    
    public void setCdrGuid(String cdrGuid) {
        this.cdrGuid = cdrGuid;
    }
    public String getCallIdentifier() {
        return this.callIdentifier;
    }
    
    public void setCallIdentifier(String callIdentifier) {
        this.callIdentifier = callIdentifier;
    }




}


